version: '2'
services:

  # The Application
  app:
    image: 1and1internet/ubuntu-16-apache-php-7.1
    volumes:
      - ./project:/var/www/dev
      - ./codiad:/var/www/codiad
      - ./apache_conf:/etc/apache2/sites-available/000-default.conf
    environment:
      - "DB_PORT=3306"
      - "DB_HOST=database"
    ports:
        - "8080:8080"
        - "8081:8081"
    links:
        - "database:mysql"
        - "ssdb:ssdb"
        - "redis:redis"

  # The Database
  database:
    image: mysql:5.7
    volumes:
      - ./db/dev1:/var/lib/mysql:rw
    environment:
      - "MYSQL_ROOT_HOST=%"
      - "MYSQL_DATABASE=homestead"
      - "MYSQL_USER=homestead"
      - "MYSQL_PASSWORD=secret"
      - "MYSQL_ROOT_PASSWORD=secret"

  # The PHPMYADMIN web interface
  phpmyadmin:
    image: nazarpc/phpmyadmin
    ports:
        - "8082:80"
    links:
        - "database:mysql"

  #SSDB
  ssdb:
    image: wendal/ssdb
    volumes:
     - ./ssdb:/var/lib/ssdb:rw

  #Redis
  redis:
    image: redis
    volumes:
     - ./redis:/data:rw



volumes:
  dbdata:
